server:
  port: 8001
mybatis:
  type-aliases-package: com.kebo.springcloud.po
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloudproviderdept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7003/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instance-id: springcloud-provider-8001




info:
  app.name: kebo
  company: fuchain
